# Generated by Django 5.2.6 on 2025-09-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scientific_name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "plant_id",
                    models.CharField(
                        help_text="Unique identifier for API",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sunlight",
                    models.CharField(
                        choices=[
                            ("Low Light (No direct sun)", "Low Light (No direct sun)"),
                            (
                                "Medium Light (A few hours)",
                                "Medium Light (A few hours)",
                            ),
                            ("Bright Light (6+ hours)", "Bright Light (6+ hours)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "space",
                    models.CharField(
                        choices=[
                            ("Small Pot (Windowsill)", "Small Pot (Windowsill)"),
                            ("Hanging Basket", "Hanging Basket"),
                            ("Medium Container", "Medium Container"),
                            ("Large Container (Balcony)", "Large Container (Balcony)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "care_level",
                    models.CharField(
                        choices=[
                            (
                                "Beginner (I forget to water)",
                                "Beginner (I forget to water)",
                            ),
                            (
                                "Intermediate (I can follow a schedule)",
                                "Intermediate (I can follow a schedule)",
                            ),
                            (
                                "Advanced (I love plant care)",
                                "Advanced (I love plant care)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="External image URL"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, help_text="Upload local image", upload_to="plants/"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Short catchy description", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description")),
                ("watering_frequency", models.CharField(max_length=100)),
                ("pot_size", models.CharField(max_length=100)),
                ("sunlight_needs", models.TextField()),
                ("watering_guide", models.TextField()),
                ("sunlight_guide", models.TextField()),
                ("potting_tips", models.TextField()),
                ("common_issues", models.TextField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_beginner_friendly", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Plant Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantCareGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("january_care", models.TextField(blank=True)),
                ("february_care", models.TextField(blank=True)),
                ("march_care", models.TextField(blank=True)),
                ("april_care", models.TextField(blank=True)),
                ("may_care", models.TextField(blank=True)),
                ("june_care", models.TextField(blank=True)),
                ("july_care", models.TextField(blank=True)),
                ("august_care", models.TextField(blank=True)),
                ("september_care", models.TextField(blank=True)),
                ("october_care", models.TextField(blank=True)),
                ("november_care", models.TextField(blank=True)),
                ("december_care", models.TextField(blank=True)),
                ("fertilizing_guide", models.TextField(blank=True)),
                ("pruning_guide", models.TextField(blank=True)),
                ("repotting_guide", models.TextField(blank=True)),
                ("pest_control", models.TextField(blank=True)),
                ("disease_prevention", models.TextField(blank=True)),
                ("pro_tips", models.TextField(blank=True)),
                ("common_mistakes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_guide",
                        to="plants.plant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plant",
            name="categories",
            field=models.ManyToManyField(blank=True, to="plants.plantcategory"),
        ),
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plants/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["plant_id"], name="plants_plan_plant_i_677a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["sunlight", "care_level"], name="plants_plan_sunligh_4db3d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="plants_plan_is_feat_9603ea_idx",
            ),
        ),
    ]
